### ISSUE TITLE
No sender included in emails. 

### ISSUE THREAD

**Issue by AlexanderProd** [joeyates/imap-backup#103]
I've made a backup using this tool but the but for every email inside the .mbox file theres no sender.  

im using a regular imap account and not google mail. 

How can this happen?

**Comment by drakuno** [comment]
This happened to me as well and upon inspection of the generated .mbox files, I have discovered that all `From` headers are prefixed with the `>` symbol for some reason!

All `From` headers look similar to this:
```
>From: Sender <sender@email.com>
```

Did I miss some configuration option? Why might this be happening otherwise?

**Comment by drakuno** [comment]
@robdejonge check out [dovecot's sync tool](https://wiki2.dovecot.org/Tools/Doveadm/Sync). That's what I ended up using.

**Comment by drakuno** [comment]
The .mbox file is a plain text file, if I remember correctly.

You can remove the leading `>` symbol and whitespace to restore the `From:` header. This is enough to display the sender.

However, as I mentioned, I opted for the dovecot tool instead because I was unaware if there might've be any other inconsistencies with the file.

**Comment by joeyates** [comment]
Hi @AlexanderProd 

The behaviour you are seeing here is by design - it is due to the fact that imap-backup stores email messages in the "mboxrd" format.

Unfortunately, there is no canonical source for the standard. I think the best analysis is [this one](https://web.archive.org/web/20201231011750/https://jdebp.eu/FGA/mail-mbox-formats.html).

Here's a brief run down...

As the mbox format concatenates messages, there needs to be a way of splitting the file back into its component messages. In mboxrd, **any** line that starts with 'From ' is to be considered the start of a message.

In order to avoid existing lines starting with 'From ' from being interpreted as message separators, the body of the message has to be changed. When writing a message to the mbox file, a '>' is prepended to all lines starting with 'From '. The process is reversed during the read process (in imap-backup's case, during restore).

**Comment by joeyates** [comment]
@AlexanderProd I've released a pre-release gem (4.0.0.rc1) with functionality to export single emails in their original form (with ">" prefixes removed from "From" lines).
