### ISSUE TITLE
XOAUTH2 via external command

### ISSUE THREAD

**Issue by paulgessinger** [joeyates/imap-backup#150]
My work recently moved to Exchange Online which requires the use of XAUTH2 for authentication. 

I suspect it would be possible to use something like [oauth2ms](https://github.com/harishkrupo/oauth2ms) to retrieve authentication tokens that could be used in this case.

Is this something that could be investigated?

**Comment by joeyates** [comment]
Hi @paulgessinger 

Thanks for opening the issue.

Using XOAUTH2 tokens in imap-backup looks interesting. The setup system could accept an access token as an alternative to a password. I wouldn't integrate the process of actually **fetching** the client access token, that, as you say would be done by an external command.

The problem with OAuth (with Microsoft Exchange, GMail and other providers) is that they require *each* individual user to act as though they had a custom application. If this "heavy lifting" is done elsewhere (e.g. with oauth2ms) then the additional complexity in imap-backup would be limited.

As always, Pull Requests are welcome 😀, otherwise, I'll have a look into this myself sooner or later.

**Comment by joeyates** [comment]
Hi @paulgessinger 

I've opted to recommend email-oauth2-proxy in the README for these cases.

**Comment by thucke** [comment]
Hi @joeyates 

I'm trying to get OAuth2 working with the local proxy recommended. Unfortunately I do not find the right config to getting connected unencrypted.

Any hints?

Thanks
Thomas

**Comment by joeyates** [comment]
@thucke I've written [a blog post about it](https://joeyates.info/posts/back-up-gmail-accounts-with-imap-backup-using-email-oauth2-proxy/). Hope that helps!
